#pragma once
#include "BTObjectsCoreTypes.h"

DECLARE_MULTICAST_DELEGATE(FOnCountdownTimerIsUpSignature)
DECLARE_MULTICAST_DELEGATE(FOnTryAnotherAttemptButtonReleasedSignature)
DECLARE_MULTICAST_DELEGATE(FOnApplyChangesButtonReleasedSignature)
DECLARE_MULTICAST_DELEGATE(FOnProceedButtonReleasedSignature)
DECLARE_MULTICAST_DELEGATE(FOnExitToMainMenuButtonReleasedSignature)
DECLARE_MULTICAST_DELEGATE_OneParam(FOnBackgroundMusicShouldChangeSignature, EBackgroundMusicType)
DECLARE_MULTICAST_DELEGATE_OneParam(FOnClickableCirclesCollisionsChangedSignature, bool)
